In [2]:
import requests
import pandas as pd

1. Pull in data from an API

In [3]:
r = requests.get('https://api.covidtracking.com/v1/states/daily.json')
data = r.json()
df = pd.DataFrame(data)
df.head()

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20210307,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,None,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,
1,20210307,AL,499819.0,107742.0,1931711.0,NaN,totalTestsPeopleViral,2323788.0,494.0,45976.0,...,None,-1,0,997207b430824ea40b8eb8506c19a93e07bc972e,0,0,0,0,0,
2,20210307,AR,324818.0,69092.0,2480716.0,NaN,totalTestsViral,2736442.0,335.0,14926.0,...,None,22,11,50921aeefba3e30d31623aa495b47fb2ecc72fae,0,0,0,0,0,
3,20210307,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,None,0,0,f77912d0b80d579fbb6202fa1a90554fc4dc1443,0,0,0,0,0,
4,20210307,AZ,826454.0,56519.0,3073010.0,NaN,totalTestsViral,7908105.0,963.0,57907.0,...,None,5,44,0437a7a96f4471666f775e63e86923eb5cbd8cdf,0,0,0,0,0,

2. Find and print two(ish) descriptive statistics about your data.

In [4]:
df.describe()

,date,positive,probableCases,negative,pending,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,...,total,totalTestResultsIncrease,posNeg,deathIncrease,hospitalizedIncrease,commercialScore,negativeRegularScore,negativeScore,positiveScore,score
count,2.078000e+04,2.059200e+04,9271.000000,1.329000e+04,2138.000000,2.061400e+04,17339.000000,12382.000000,11636.000000,3789.000000,...,2.078000e+04,20780.000000,2.078000e+04,20780.000000,20780.000000,20780.0,20780.0,20780.0,20780.0,20780.0
mean,2.020244e+07,1.651560e+05,21729.123719,8.482246e+05,1659.862956,2.186936e+06,1190.576965,9262.762478,359.621176,1934.191607,...,7.063208e+05,17508.388210,7.061500e+05,24.790712,37.360780,0.0,0.0,0.0,0.0,0.0
std,3.608732e+03,3.267852e+05,45471.459778,1.344501e+06,4671.028548,4.436508e+06,2060.041207,12620.544081,594.831150,1953.329983,...,1.300339e+06,33586.022461,1.299997e+06,60.162742,208.237151,0.0,0.0,0.0,0.0,0.0
min,2.020011e+07,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.000000,0.000000,6.000000,...,0.000000e+00,-130545.000000,0.000000e+00,-201.000000,-12257.000000,0.0,0.0,0.0,0.0,0.0
25%,2.020060e+07,5.753750e+03,773.500000,5.394125e+04,43.000000,1.040498e+05,166.500000,985.250000,60.000000,501.000000,...,2.577975e+04,1205.750000,2.565875e+04,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
50%,2.020090e+07,4.606450e+04,4491.000000,3.059720e+05,212.500000,6.552670e+05,531.000000,4472.000000,172.000000,1295.000000,...,1.937255e+05,6125.000000,1.935810e+05,6.000000,0.000000,0.0,0.0,0.0,0.0,0.0
75%,2.020120e+07,1.779580e+05,19553.000000,1.056611e+06,1295.750000,2.264766e+06,1279.000000,12248.500000,380.000000,2451.000000,...,7.737408e+05,19086.500000,7.737408e+05,24.000000,36.000000,0.0,0.0,0.0,0.0,0.0
max,2.021031e+07,3.501394e+06,365961.000000,1.018694e+07,64400.000000,4.964601e+07,22851.000000,82237.000000,5225.000000,9263.000000,...,1.125679e+07,473076.000000,1.124825e+07,2559.000000,16373.000000,0.0,0.0,0.0,0.0,0.0

In [5]:
df.shape

(20780, 56)

In [6]:
df.info

<bound method DataFrame.info of            date state  positive  probableCases   negative  pending  \
0      20210307    AK   56886.0            NaN        NaN      NaN
1      20210307    AL  499819.0       107742.0  1931711.0      NaN
2      20210307    AR  324818.0        69092.0  2480716.0      NaN
3      20210307    AS       0.0            NaN     2140.0      NaN
4      20210307    AZ  826454.0        56519.0  3073010.0      NaN
...         ...   ...       ...            ...        ...      ...
20775  20200117    WA       0.0            NaN        NaN      NaN
20776  20200116    WA       0.0            NaN        NaN      NaN
20777  20200115    WA       0.0            NaN        NaN      NaN
20778  20200114    WA       0.0            NaN        NaN      NaN
20779  20200113    WA       NaN            NaN        NaN      NaN

         totalTestResultsSource  totalTestResults  hospitalizedCurrently  \
0               totalTestsViral         1731628.0                   33.0
1         totalTestsPeopleViral         2323788.0                  494.0
2               totalTestsViral         2736442.0                  335.0
3               totalTestsViral            2140.0                    NaN
4               totalTestsViral         7908105.0                  963.0
...                         ...               ...                    ...
20775  totalTestEncountersViral               NaN                    NaN
20776  totalTestEncountersViral               NaN                    NaN
20777  totalTestEncountersViral               NaN                    NaN
20778  totalTestEncountersViral               NaN                    NaN
20779  totalTestEncountersViral               NaN                    NaN

       hospitalizedCumulative  ...  dataQualityGrade  deathIncrease  \
0                      1293.0  ...              None              0
1                     45976.0  ...              None             -1
2                     14926.0  ...              None             22
3                         NaN  ...              None              0
4                     57907.0  ...              None              5
...                       ...  ...               ...            ...
20775                     NaN  ...              None              0
20776                     NaN  ...              None              0
20777                     NaN  ...              None              0
20778                     NaN  ...              None              0
20779                     NaN  ...              None              0

       hospitalizedIncrease                                      hash  \
0                         0  dc4bccd4bb885349d7e94d6fed058e285d4be164
1                         0  997207b430824ea40b8eb8506c19a93e07bc972e
2                        11  50921aeefba3e30d31623aa495b47fb2ecc72fae
3                         0  f77912d0b80d579fbb6202fa1a90554fc4dc1443
4                        44  0437a7a96f4471666f775e63e86923eb5cbd8cdf
...                     ...                                       ...
20775                     0  7cefac6b3681020741ca30f45399a7b22f2e45b4
20776                     0  650501e005a5ee86d93c5f32dda56735ea2af967
20777                     0  4987e61aad88182abfe641033b597304c2153d4f
20778                     0  1881c8a2f0d337b22066b4f05df06eb2259e8d57
20779                     0  12b994ad07c276a5278a2465e081751688739765

       commercialScore negativeRegularScore negativeScore positiveScore  \
0                    0                    0             0             0
1                    0                    0             0             0
2                    0                    0             0             0
3                    0                    0             0             0
4                    0                    0             0             0
...                ...                  ...           ...           ...
20775                0                    0             0             0
20776                0                    0             0             0
20777                0                    0             0             0
20778                0                    0             0             0
20779                0                    0             0             0

       score  grade
0          0
1          0
2          0
3          0
4          0
...      ...    ...
20775      0
20776      0
20777      0
20778      0
20779      0

[20780 rows x 56 columns]>

3. Write a query in Pandas to select a particular set of your data.

In [7]:
df[df['state'] == 'KY']

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
19,20210307,KY,410709.0,96324.0,NaN,NaN,totalTestsViral,3975672.0,558.0,19457.0,...,None,13,6,e75efcdb394b4f605892102108def98f76e402d4,0,0,0,0,0,
75,20210306,KY,410184.0,96186.0,NaN,NaN,totalTestsViral,3975672.0,591.0,19451.0,...,None,52,71,b40155b94de8b72d0fc694be25c6bd0046d2f2da,0,0,0,0,0,
131,20210305,KY,409345.0,95854.0,NaN,NaN,totalTestsViral,3969899.0,606.0,19380.0,...,None,22,16,c5d4da20edd9c8e824ab508742b2b62cd6974d3e,0,0,0,0,0,
187,20210304,KY,408440.0,95510.0,NaN,NaN,totalTestsViral,3954639.0,645.0,19364.0,...,None,28,60,a77d9dfcb7c88e8b9111abba9bf70fc2b9f3726a,0,0,0,0,0,
243,20210303,KY,407373.0,95194.0,NaN,NaN,totalTestsViral,3940366.0,680.0,19304.0,...,None,33,70,b261d9c206a6b0aec2d561ad92736ab846f76036,0,0,0,0,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20264,20200310,KY,6.0,NaN,NaN,NaN,totalTestsViral,34.0,NaN,NaN,...,None,0,0,82ffc3201047d35185e5e187b4a73dade8366710,0,0,0,0,0,
20315,20200309,KY,4.0,NaN,NaN,NaN,totalTestsViral,21.0,NaN,NaN,...,None,0,0,852700175611a54142c26a9aef1872a97ddd70c5,0,0,0,0,0,
20366,20200308,KY,1.0,NaN,NaN,NaN,totalTestsViral,14.0,NaN,NaN,...,None,0,0,ebab6b1a9375f06e3d6213f2eff513dce681d49c,0,0,0,0,0,
20417,20200307,KY,1.0,NaN,NaN,NaN,totalTestsViral,10.0,NaN,NaN,...,None,0,0,4f49b56df3e288a4c6611193f53ef61677bae493,0,0,0,0,0,
20466,20200306,KY,0.0,NaN,NaN,3.0,totalTestsViral,7.0,NaN,NaN,...,None,0,0,f44300a9cd7225371832b11e8315b93e8eb19a7c,0,0,0,0,0,

4. Select and print the SECOND AND THIRD columns of your data frame.

In [8]:
df.iloc[:,1:3]

      state  positive
0        AK   56886.0
1        AL  499819.0
2        AR  324818.0
3        AS       0.0
4        AZ  826454.0
...     ...       ...
20775    WA       0.0
20776    WA       0.0
20777    WA       0.0
20778    WA       0.0
20779    WA       NaN

[20780 rows x 2 columns]

5. Select and print the FIRST 4 rows of you data frame.

In [9]:
df.head(4)

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20210307,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,None,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,
1,20210307,AL,499819.0,107742.0,1931711.0,NaN,totalTestsPeopleViral,2323788.0,494.0,45976.0,...,None,-1,0,997207b430824ea40b8eb8506c19a93e07bc972e,0,0,0,0,0,
2,20210307,AR,324818.0,69092.0,2480716.0,NaN,totalTestsViral,2736442.0,335.0,14926.0,...,None,22,11,50921aeefba3e30d31623aa495b47fb2ecc72fae,0,0,0,0,0,
3,20210307,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,None,0,0,f77912d0b80d579fbb6202fa1a90554fc4dc1443,0,0,0,0,0,